apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "reviews"
  namespace: "{{ .Values.bookinfo.namespace }}"
spec:
  destination:
    namespace: "{{ .Values.bookinfo.namespace }}"
    server: "{{ .Values.spec.destination.server }}"
  project: "{{ .Values.spec.project }}"
  source:
    path: reviews
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.revision }}"
